import { Col, Container, Row } from "react-bootstrap";
import PageHero from "../components/PageHero";
import bloodPotion from "../assets/items/blood-potion.png";
import thistle from "../assets/items/thistle.webp";

const hungerGamesChest = "https://static.wikia.nocookie.net/vrising/images/1/10/Structure_SmallStash.png/revision/latest?cb=20220529172626";
const horseSaddle = "https://static.wikia.nocookie.net/vrising/images/b/be/Item_VampireHorseSaddle.png/revision/latest?cb=20230519050550";

type EventCardProps = { title: string; image: string; imageAlt: string; intro: string; rules: string[]; reward: string; command?: string };

function EventCard({ title, image, imageAlt, intro, rules, reward, command }: EventCardProps) {
  return <article className="event-card"><div className="event-card-heading"><div className="event-icon"><img src={image} alt={imageAlt} /></div><div><div className="eyebrow">Server event</div><h2>{title}</h2></div></div><p className="event-intro">{intro}</p>{command && <code className="event-command">{command}</code>}<h3>How it works</h3><ul className="event-list">{rules.map((rule) => <li key={rule}>{rule}</li>)}</ul><div className="event-reward"><img src={thistle} alt="Thistle" /><strong>Reward</strong><span>{reward}</span></div></article>;
}

export default function Events() {
  return <><PageHero eyebrow="Server activities" title="Black Vein events." description="Quick, competitive server events with clear rules and Virtual Thistle rewards." />
    <section className="section pt-4"><Container><div className="event-rules-panel"><div className="eyebrow">Read before joining</div><h2>Event rules</h2><p>Keep it simple: have fun, play competitively, and respect everyone taking part.</p><Row className="g-3"><Col md={4}><div className="event-rule"><span>01</span><h3>Play with your assigned team</h3><p>Team only with the teammate(s) assigned for that event. Other players or clans are off-limits unless an admin says otherwise.</p></div></Col><Col md={4}><div className="event-rule"><span>02</span><h3>Rules are enforced</h3><p>Breaking an event rule means immediate elimination from the event.</p></div></Col><Col md={4}><div className="event-rule"><span>03</span><h3>Keep the event fair</h3><p>Do not sabotage other participants. Repeated disruption can exclude you from future events. Leave grudges and alliances outside.</p></div></Col></Row></div></Container></section>
    <section className="section pt-0"><Container><div className="section-heading"><div><div className="eyebrow">Regular server events</div><h2>Events available on Black Vein.</h2></div><p>These are the regular event formats hosted on the server. The next start time is always announced on Discord.</p></div><Row className="g-4"><Col lg={4}><EventCard title="Hunger Games" image={hungerGamesChest} imageAlt="V Rising small chest" intro="Start with nothing, search for loot, and be the final team standing as the safe zone closes in." rules={["Teams of 2 players.", "No starting gear. Find weapons, armour, and consumables in chests.", "Fight, loot, and survive while the safe zone gradually shrinks.", "A match lasts around 5 to 10 minutes."]} reward="300 Thistles for the last surviving team." /></Col><Col lg={4}><EventCard title="Horse Event" image={horseSaddle} imageAlt="V Rising vampire horse saddle" intro="Find the marked horse, steal it, and get it safely into a closed room in your castle." rules={["An icon on the map marks the event horse once it starts.", "Deliver the horse to a closed room inside your castle.", "PvP is fully enabled, but there is no PvP durability loss.", "The first team to deliver its horse wins."]} reward="300 Thistles for the winning player." /></Col><Col lg={4}><EventCard title="Blood Bank" image={bloodPotion} imageAlt="Blood potion" intro="A 3-player PvP event using your own V Arena builds. Protect your score and take points from opponents." command=".import <build>" rules={["Teams are made from 3 random players to balance skill.", "Import your V Arena build before the event starts.", "Your Gear Score is your points; eliminations steal 50% of a player's current points.", "PvP is enabled for around 5 to 10 minutes; highest team score wins."]} reward="300 Thistles for the winning team." /></Col></Row></Container></section>
    <section className="section pt-0"><Container><div className="events-upcoming-note"><div className="eyebrow">Server activities</div><h2>More events will be posted soon.</h2><p>Event details, start times and rewards will be announced on Discord.</p></div></Container></section>
    <section className="section section-dark pt-0"><Container><div className="event-credits"><div><div className="eyebrow">Credits</div><h2>Community tools &amp; mods</h2></div><div className="credit-item"><strong>Event mods</strong><span>Created by <b>@ModMan</b></span></div><div className="credit-item"><strong>V Arena</strong><span>Build tools and arena website by <b>@rendy</b></span><a href="https://www.v-arena.com/" target="_blank" rel="noreferrer">Visit V Arena <span aria-hidden="true">↗</span></a></div></div></Container></section>
  </>;
}
