import { useMemo, useState } from "react";
import { Col, Container, Row } from "react-bootstrap";
import PageHero from "../components/PageHero";
type Signal = { title: string; category: "Drop" | "Session" | "Community"; date: string; text: string };
const signals: Signal[] = [
  { title: "Night shift: open session", category: "Session", date: "SEP 18", text: "A low-key room for big ideas, fresh work and unexpected connections." },
  { title: "The Unseen collection", category: "Drop", date: "SEP 09", text: "A new limited release, created for the part of the story beneath the surface." },
  { title: "Member spotlight: Mira", category: "Community", date: "AUG 29", text: "Meet the visual storyteller bringing a restless, thoughtful eye to the collective." },
  { title: "Signal zero recap", category: "Session", date: "AUG 12", text: "A look back at the first gathering and the questions that carried forward." },
  { title: "Building in public", category: "Community", date: "AUG 03", text: "Five members on how they turn a rough spark into a project with momentum." },
  { title: "Afterimage // 01", category: "Drop", date: "JUL 22", text: "A visual study in contrast, movement and the residue of bright things." },
];
export default function Pulse() { const [query, setQuery] = useState(""); const [category, setCategory] = useState("All"); const results = useMemo(() => signals.filter(s => (category === "All" || s.category === category) && `${s.title} ${s.text}`.toLowerCase().includes(query.toLowerCase())), [category, query]); return <><PageHero eyebrow="The pulse" title="What's moving through Black Vein." description="A living feed of drops, sessions, stories and signals from the community." /><section className="section pt-4"><Container><Row className="mb-4 g-3"><Col md={7}><input className="filter-control" aria-label="Search signals" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search the pulse..." /></Col><Col md={5}><select className="filter-control" aria-label="Filter by category" value={category} onChange={e => setCategory(e.target.value)}><option>All</option><option>Drop</option><option>Session</option><option>Community</option></select></Col></Row><p className="text-secondary small mb-4">{results.length} {results.length === 1 ? "signal" : "signals"} found</p><Row className="g-4">{results.map(signal => <Col md={6} lg={4} key={signal.title}><article className="pulse-card"><div className="d-flex justify-content-between align-items-center mb-4"><span className="tag">{signal.category}</span><time>{signal.date}</time></div><h3>{signal.title}</h3><p className="mb-0">{signal.text}</p></article></Col>)}</Row>{!results.length && <div className="empty-state">No signal matches that search. Try a different word or category.</div>}</Container></section></>; }
